# Site settings
title: Erin Bionda
description: 'University of Toronto graduate. Bachelor of Commerce, specializing in marketing.'

author:
  name: 'Erin Bionda'
  email: erin.bionda@hotmail.com 
  linkedin_username: erinbionda

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
